import os

PROJECT_ID = ''

CLOUDSQL_USER = ''
CLOUDSQL_PASSWORD = ''
CLOUDSQL_DATABASE = ''
CLOUDSQL_CONNECTION_NAME = ''
LOCAL_SQLALCHEMY_DATABASE_URI = ('mysql+pymysql://{user}:{password}@127.0.0.1:3306/{database}').format(user=CLOUDSQL_USER, password=CLOUDSQL_PASSWORD,database=CLOUDSQL_DATABASE)
LIVE_SQLALCHEMY_DATABASE_URI = ('mysql+pymysql://{user}:{password}@localhost/{database}?unix_socket=/cloudsql/{connection_name}').format(user=CLOUDSQL_USER, password=CLOUDSQL_PASSWORD,database=CLOUDSQL_DATABASE, connection_name=CLOUDSQL_CONNECTION_NAME)
if os.environ.get('GAE_INSTANCE'):
	SQLALCHEMY_DATABASE_URI = LIVE_SQLALCHEMY_DATABASE_URI
else:
	SQLALCHEMY_DATABASE_URI = LOCAL_SQLALCHEMY_DATABASE_URI

SECRET_KEY = ''
SECURITY_PASSWORD_SALT = ''
MAIL_SERVER = ""
MAIL_PORT = 999
MAIL_USERNAME = ''
MAIL_PASSWORD = ''
MAIL_DEFAULT_SENDER = ''
MAIL_DEFAULT_SENDERNAME = ''

MAX_PAIR = 0
MAX_ANSWER = 0